title: "Guerra Civil Brasileira Bot, por GGValdez"
description: "Algorítimo feito por fans da página Guerra Civil Brasileira Bot"

# see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
lang: 'pt'

#plugins:
#  - jemoji